---
local_db: sqlite3:/var/vcap/services/maglev/maglev_node.db
mbus: nats://localhost:4222
base_dir: /var/vcap/services/maglev/
log_level: DEBUG
pid: /var/vcap/sys/run/maglev_node.pid
available_memory: 4096
node_id: maglev_node_1
max_memory: 512
maglev_home: /home/maglev/Maglev/maglev
