---
# cloud_controller_uri: api.vcap.me
service:
  name: maglev
  version: "0.8"
  description: 'MagLev Stone Service'
  plans: ['free']
  tags: ['maglev', 'maglev-0.8', 'stone']
host: localhost
token: "0xdeadbeef"
log_level: DEBUG
mbus: nats://localhost:4222
pid: /var/vcap/sys/run/maglev_service.pid
node_timeout: 2
